### ISSUE TITLE
Something wrong on linux: libjpeg.so.9

### ISSUE THREAD

**Issue by xigrug** [NASA-DEVELOP/VOCAL#132]
## Linux c03n02 2.6.32-696.16.1.el6.x86_64 #1 SMP Wed Nov 15 16:51:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**python Calipso.py**
Traceback (most recent call last):
  File "Calipso.py", line 15, in <module>
    from tools.loaddata import LoadData
  File "/data/c03n02/cliu/src/VOCAL-master/calipso/tools/loaddata.py", line 9, in <module>
    from ccplot.hdf import HDF
ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory
(cc_plot) [cliu@c03n02 calipso]$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import ccplot
>>> import ccplot.hdf import hdf
  File "<stdin>", line 1
    import ccplot.hdf import hdf
                           ^
SyntaxError: invalid syntax
>>> from ccplot.hdf import hdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory**
—————————————————————————————————————
 **## ln -s ~/soft/anaconda2/lib/libjpeg.so.9 .**
 **python Calipso.py**
[2018-05-15 16:52:51,152] [    INFO] --- Instantiating DatabaseManager... (db.py:108)
./../db/CALIPSOdb.db
[2018-05-15 16:52:52,186] [    INFO] --- No tags found, setting base case... (db.py:131)
[2018-05-15 16:52:52,186] [    INFO] --- Found unique tag 0... (db.py:137)
[2018-05-15 16:52:52,199] [    INFO] --- Debug Level = 1... (Calipso.py:917)
[2018-05-15 16:52:52,199] [    INFO] --- Starting CALIPSO program... (Calipso.py:920)
[2018-05-15 16:52:53,835] [    INFO] --- Instantiate CALIPSO program... (Calipso.py:923)
[2018-05-15 16:52:53,910] [    INFO] --- Intializing File: Empty... (loaddata.py:23)
[2018-05-15 16:52:53,910] [   **ERROR**] --- File not found or not useful...... (loaddata.py:31)
[2018-05-15 16:52:53,910] [    INFO] --- Screen resolution: 1368x912... (Calipso.py:87)
[2018-05-15 16:52:54,828] [    INFO] --- Creating ToolsWindow... (Calipso.py:118)
[2018-05-15 16:52:54,840] [    INFO] --- Creating ShapeManager... (Calipso.py:120)
[2018-05-15 16:52:54,840] [    INFO] --- Defining initial shape manager... (manager.py:35)
[2018-05-15 16:52:54,840] [    INFO] --- Instantiating Exporting Reader... (manager.py:44)
[2018-05-15 16:52:54,841] [    INFO] --- Querying database for unique tag... (manager.py:50)
[2018-05-15 16:52:54,841] [    INFO] --- Binding matplotlib backend to canvas and frame... (Calipso.py:123)
[2018-05-15 16:52:54,985] [    INFO] --- Setting up window... (Calipso.py:927)
[2018-05-15 16:52:54,985] [    INFO] --- Linux system detected... (Calipso.py:213)
[2018-05-15 16:52:54,986] [    INFO] --- Setting up menu... (Calipso.py:929)
[2018-05-15 16:52:55,070] [    INFO] --- Setting up main screen... (Calipso.py:931)
[2018-05-15 16:52:55,070] [    INFO] --- Creating upper program GUI... (Calipso.py:241)
[2018-05-15 16:52:55,081] [    INFO] --- Setting up toolbar... (toolswindow.py:85)
[2018-05-15 16:52:55,129] [    INFO] --- Creating toolbar buttons... (toolswindow.py:145)
[2018-05-15 16:52:55,191] [    INFO] --- Button pressed - ploygon... (toolswindow.py:201)
[2018-05-15 16:52:55,234] [    INFO] --- Setting initial plot... (Calipso.py:271)
[2018-05-15 16:52:55,235] [ WARNING] --- set_plot called for BASE_PLOT... (manager.py:591)
[2018-05-15 16:52:55,235] [   ERROR] --- <type 'exceptions.AttributeError'>: __exit__... (log.py:49)
None
[2018-05-15 16:52:55,278] [   ERROR] ---   File "Calipso.py", line 939, in <module>
    main()
  File "Calipso.py", line 932, in main
    program.setup_main_screen()
  File "Calipso.py", line 272, in setup_main_screen
    self.set_plot(Plot.baseplot, 0)
  File "Calipso.py", line 462, in set_plot
    im = mpimg.imread(PATH + '/dat/CALIPSO.jpg')
  File "/users1j/cliu/soft/anaconda2/envs/cc_plot/lib/python2.7/site-packages/matplotlib/image.py", line 1278, in imread
    im = pilread(fname)
  File "/users1j/cliu/soft/anaconda2/envs/cc_plot/lib/python2.7/site-packages/matplotlib/image.py", line 1256, in pilread
    with Image.open(fname) as image:
  File "/users1j/cliu/soft/anaconda2/envs/cc_plot/lib/python2.7/site-packages/PIL/Image.py", line 512, in __getattr__
    raise AttributeError(name)
... (log.py:50)
None

**Comment by Syntaf** [comment]
Pillow is notoriously good at breaking their own package. I'd recommend trying to downgrade the pillow version and see if earlier versions work with VOCAL.
