### ISSUE TITLE
Installation and launching in Win-64 OS

### ISSUE THREAD

**Issue by HARSHBARDHANK94** [NASA-DEVELOP/VOCAL#136]
I have successfully installed the following prerequisites: **python: 3.8.5,  pillow: 8.0.1, numpy: 1.19.2, basemap: 1.2.2+dev, ccplot: 1.5.6** and ccplot is working fine as I made a plot with it. And also downloaded the VOCAL zip from https://github.com/NASA-DEVELOP/VOCAL.
but am facing error in launching it, may be I am doing something wrong. some folder path screenshots is shown below: 

![Screenshot (958)](https://user-images.githubusercontent.com/85699193/135969303-74575073-be0b-47f0-9f62-21c8272479dd.png)

![Screenshot (959)](https://user-images.githubusercontent.com/85699193/135969297-3cbeee5f-2ac4-4a24-95e8-edad1f452ee2.png)
![Screenshot (960)](https://user-images.githubusercontent.com/85699193/135969301-e37319fd-fd5a-444f-aec1-c45620643749.png)
![Screenshot (957)](https://user-images.githubusercontent.com/85699193/135969302-72e4ddca-941c-425a-854d-27e499853565.png)

**Comment by HARSHBARDHANK94** [comment]
(base) C:\Users\HARSHBARDHAN>python VOCAL\calipso\Calipso.py
VOCAL\calipso\Calipso.py:730: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if f is '':

**Traceback (most recent call last):
  File "C:\Users\HARSHBARDHAN\VOCAL\calipso\tools\config.py", line 114, in get_config
    with open(self.__file) as json_data_file:
FileNotFoundError: [Errno 2] No such file or directory: './dat/config.json'**


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "VOCAL\calipso\Calipso.py", line 15, in <module>
    from tools.loaddata import LoadData
  File "C:\Users\HARSHBARDHAN\VOCAL\calipso\tools\loaddata.py", line 11, in <module>
    import constants
  File "C:\Users\HARSHBARDHAN\VOCAL\calipso\constants.py", line 79, in <module>
    CONF = Config(PATH + '/dat/config.json')
  File "C:\Users\HARSHBARDHAN\VOCAL\calipso\tools\config.py", line 105, in __init__
    self.get_config()
  File "C:\Users\HARSHBARDHAN\VOCAL\calipso\tools\config.py", line 119, in get_config
    self.write_config()
  File "C:\Users\HARSHBARDHAN\VOCAL\calipso\tools\config.py", line 136, in write_config
    for key, value in var_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by HARSHBARDHANK94** [comment]
FileNotFoundError: [Errno 2] No such file or directory: './dat/config.json'

**Comment by HARSHBARDHANK94** [comment]
Anyone please guide to do it properly.
